services:
  manemix:
    environment:
      - MANEMIX_URL=https://${DOMAIN}

  web:
    volumes:
      - ./conf/nginx/prod.conf:/etc/nginx/templates/default.conf.template:ro
      - ./static/:/usr/share/manemix/static/:ro
      - manemix-data:/var/lib/manemix:ro
      - certbot-webroot:/var/www/certbot:ro
      - certbot-certs:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot-webroot:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - web

  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  certbot-webroot:
  certbot-certs:
